/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cif.mllearning.components;

import javax.swing.JOptionPane;

/**
 *
 * @author 10797
 */
public class PlotTopPanel extends javax.swing.JPanel {

    private PlotPanel plotPanel;

    /**
     * Creates new form PlotTopPanel
     */
    public PlotTopPanel(PlotPanel plotPanel) {
        initComponents();
        this.plotPanel = plotPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accuracyBtn = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(accuracyBtn, org.openide.util.NbBundle.getMessage(PlotTopPanel.class, "PlotTopPanel.accuracyBtn.text")); // NOI18N
        accuracyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accuracyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 167, Short.MAX_VALUE)
                .addComponent(accuracyBtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accuracyBtn)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accuracyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accuracyBtnActionPerformed
        // TODO add your handling code here:

//        JOptionPane.showMessageDialog(this, "Accuracy！");
        plotPanel.getAccuracy();
    }//GEN-LAST:event_accuracyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accuracyBtn;
    // End of variables declaration//GEN-END:variables
}
