/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cif.mllearning.components;

import javax.swing.JOptionPane;

/**
 *
 * @author 10797
 */
public class PlotTopPanel extends javax.swing.JPanel {

    private PlotPanel plotPanel;

    /**
     * Creates new form PlotTopPanel
     */
    public PlotTopPanel(PlotPanel plotPanel) {
        initComponents();
        this.plotPanel = plotPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accuracyBtn = new javax.swing.JButton();
        loadResult = new javax.swing.JButton();
        loadRightResult = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(accuracyBtn, org.openide.util.NbBundle.getMessage(PlotTopPanel.class, "PlotTopPanel.accuracyBtn.text")); // NOI18N
        accuracyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accuracyBtnActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(loadResult, org.openide.util.NbBundle.getMessage(PlotTopPanel.class, "PlotTopPanel.loadResult.text")); // NOI18N
        loadResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadResultActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(loadRightResult, org.openide.util.NbBundle.getMessage(PlotTopPanel.class, "PlotTopPanel.loadRightResult.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(loadResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadRightResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accuracyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(accuracyBtn)
                .addComponent(loadResult)
                .addComponent(loadRightResult))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accuracyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accuracyBtnActionPerformed
        // TODO add your handling code here:

//        JOptionPane.showMessageDialog(this, "Accuracy！");
        plotPanel.getAccuracy();
    }//GEN-LAST:event_accuracyBtnActionPerformed

    private void loadResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadResultActionPerformed
        // TODO add your handling code here:
        plotPanel.loadAndPaintClassifyRes("分类结果",plotPanel.dataSourceIndex);
        plotPanel.loadAndPaintClusterRes("聚类结果",plotPanel.dataSourceIndex);
    }//GEN-LAST:event_loadResultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accuracyBtn;
    private javax.swing.JButton loadResult;
    private javax.swing.JButton loadRightResult;
    // End of variables declaration//GEN-END:variables
}
